server:
  port:
    8081
logging:
  level:
    root: "warn"
    org.springframework.web: "error"
    org.hibernate: "error"
spring:
  cloud:
    vault:
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      scheme: http
      host: vault
      port: 8200
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: tutor-backend
      database:
        enabled: true
        role: dynamic-role
  datasource:
    url: jdbc:postgresql://db:5432/tutoraspsqldb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
